apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: document-processor-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/document-processor-infra
    targetRevision: main
    path: charts/document-processor
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: document-processor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

